folio-org/ui-tenant-settings

CHANGELOG.md, src/settings/ServicePoints/ServicePointForm.js, src/settings/ServicePoints/ServicePointManager.js
In the service points form, the setting of print-default booleans
for staff-slips is effectively done by position and relies
on the ordering of the booleans being the same as the ordering of
the staffslips names. This commit aims to ensure, they are ordered
the same (by staffslip name).
=> Fix ordering of staffslips names and booleans UIORG-167

CHANGELOG.md, src/settings/LocationLocations/LocationForm.js, src/settings/LocationLocations/LocationManager.js, src/settings/ServicePoints/ServicePointManager.js
Permissions were renamed when the module was renamed but we missed this
in a few places.
Fixes [UIORG-172](https://issues.folio.org/browse/UIORG-172)
=> use correct permission names

src/settings/Addresses.css, src/settings/Addresses.js
Make the acquisitions addresses retain line breaks
https://issues.folio.org/browse/UIOR-296
add property `white-space: pre-line` to address block
=> UIOR-296 Make the acq addresses retain line breaks

CHANGELOG.md, src/settings/ServicePoints/ServicePointDetail.js, src/settings/ServicePoints/ServicePointManager.js
When retrieving the locations related to a service-point, retrieve up to
1,000 instead of the default, 10.
Fixes [UITEN-43](https://issues.folio.org/browse/UITEN-43)
=> UITEN-43 retrieve additional locations

package.json
Access to tenant settings was inadvertently removed in #31. We don't
need `settings.tenant-settings.enabled` to be a visible permission, but we do
need it to be present so that stripes-core will discover that this
module has settings.
Refs [UITEN-44](https://issues.folio.org/browse/UITEN-44)
=> UITEN-44 restore settings

package.json
"location-units" version bumped to '2.0'
=> UITEN-61: Fix the impact of the API change as per MODINVSTOR-315 for ui-tenant-settings.

CHANGELOG.md, src/settings/Locale.js, test/bigtest/helpers/turn-off-warnings.js, test/bigtest/index.js, test/bigtest/tests/language-and-localization-test.js, translations/ui-tenant-settings/en.json
Provide a link from the tenant-locale page to the ui-developer
session-locale page in the hope that folks will use that instead.
Refs [UITEN-53](https://issues.folio.org/browse/UITEN-53)
=> UITEN-53 provide link to session-locale settings

src/settings/Locale.js
French (France) is already a translation pulled from Lokalise to GitHub; it wasn't in the locale menu selection.
=> Add French (France) to locale menu

CHANGELOG.md, package.json
Update 
`stripes` to `v3.0.0`, 
`stripes-core` to `4.0.0`,
`react-intl` to `2.9.0`
[UITEN-83](https://issues.folio.org/browse/UITEN-83)
Please, update your core `package.json`:
```javascript
"dependencies": {
"@folio/stripes": "^3.0.0"
},
"resolutions": {
"@folio/stripes": "^3.0.0"
}
```
=> UITEN-83: Update stripes to v3.0.0

src/settings/LocationLocations/LocationDetail.js, test/ui-testing/locations.js
Restore `id` attributes to the action menu items so we can find them in
tests. Happy tests!
=> restore delete-button element-ids

src/settings/LocationLocations/LocationManager.js
https://issues.folio.org/browse/UITEN-81
Refinement of the functionality implemented by the [80ce58d](https://github.com/folio-org/ui-tenant-settings/commit/80ce58dbcf1e0fe21bedb67ad3002c8ff0892321) in order to provide the 'isActive' property to all 'locations' where it's missing.
=> UITEN-81: Add 'isActive' property to all 'locations' where it's missing

src/settings/LocationLocations/LocationManager.js
Continued #115 and #118.
As a result of the discussion in the comments to [UITEN-81](https://issues.folio.org/browse/UITEN-81), it was decided to adhere to the following approach:
> When isActive is present and true, the status should be Active. When isActive is (a) present and false or (b) absent, the status should be Inactive.
=> UITEN-81: Set default isActive property to false if it's missing

CHANGELOG.md, src/settings/Plugins/Plugins.js
Use `==` instead of `=` when possible for more efficient queries.
Refs [PERF-62](https://issues.folio.org/browse/PERF-62)
=> PERF-62 use == for more efficient queries

CHANGELOG.md, src/settings/Locale.js, test/bigtest/tests/language-and-localization-test.js
Managing the translation values for locales was confusing because we
want to show "lang-A/lang-B" where lang-A is the locale in the current
locale and lang-B is the locale in that locale. For example, when the
current locale is English and the value is Russian, we want to show
`Russian / русский`, and when the value is Japanese, we want to show
`Japanese / 日本語`.
Rather than getting these values via translations, we can derive them
from react-intl directly.
Refs [UITEN-105](https://issues.folio.org/browse/UITEN-105)
=> UITEN-105 correctly show locales in native locale

CHANGELOG.md, test/ui-testing/test.js
I love this test. It is my favorite test in all off my nightmare tests.
I love this test the most because it always succeeds when I run it in
isolation and always fails when I run it as part of the suite. This
makes it extra special and extra deserving of my love. NightmareJS and
consistent test results walk hand in hand together like love, marriage,
and ritual infanticide. A test is a test of course, I Jest, and no one
can talk to a test unless, that is, oh hell, unless you spell, your test
like R-T-L. What if the BigTest is not big enough? _He cries_. Writing
more tests in NightmareJS will liquify the nerves of the sentient beings
*it begins*. It is a journey. It is a journey up a river of c͒ͪo͛ͫrruption.
*_He comes_*. It is a journey across the water in search of a m̡adman,
in se̶arch …
=> FOLIO-2727 temporarily disable flakey tests

CHANGELOG.md, src/settings/Locale.js
A few days ago, FormatJS made the `type` option required on its DisplayNameOptions object. Since their environment/code is typescript, their code can move along assuming it will be there - but in our case it wasn't which caused some ugly crashes when entering a page that rendered a list of locales both ui-developer and ui-tenant-settings were affected, far as I see...
Simply adding the display options object with a `type` parameter of `language` resolved the issue.
Browser API under the hood holds the options as optional, but all of their examples have something set... It even defaults to 'language' if you pass nothing, but not at the layer of react-intl where the problem resides...
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/DisplayNa …
=> Pass required options object to FormatDisplayName

CHANGELOG.md, package.json
Add extra `login-saml.regenerate` permission so the download metadata button works correctly.
https://issues.folio.org/browse/UITEN-70
=> UITEN-70: Add extra permission for download metadata button

CHANGELOG.md, package.json, translations/ui-tenant-settings/en.json
[[UITEN-115]](https://issues.folio.org/browse/UITEN-115)
Make permission names localizable.
=> UITEN-115: Make permission names localizable

CHANGELOG.md, src/settings/SSOSettings/SamlForm.js, test/bigtest/interactors/sso-settings.js, test/bigtest/tests/sso-settings-test.js
https://issues.folio.org/browse/UITEN-123
Disable Download metadata button when url is not provided.
=> UITEN-123: Disable Download metadata button when url is not provided

src/settings/SSOSettings/SamlForm.js
https://issues.folio.org/browse/UITEN-123
This is an additional small change based on the feedback in UITEN-123 to only show download button in cases when the form is saved successfully.
=> UITEN-123: Only show download button after successful form submission

CHANGELOG.md, package.json, src/settings/LocationLocations/LocationManager.js
In short, this PR removes checks for dangling references from
course-reserves, an optional Okapi module. It does so because, as that
module is optional and this one is required, this one sits below it in
the hierarchy of modules and therefore cannot know about the interfaces,
and more importantly, the permissions required to access the endpoints
defined by those interfaces. Thus, even though the queries were
protected correctly by `stripes.ifInterface(...)` conditions, the
queries would still fail because there was no way for the
location-managment pset (`ui-tenant-settings.settings.location`) to
include those permissions.
I feel bad removing this code -- which, to be clear, does its job
perfectly cromulently -- but I have to because there is no way (at least
at present) for it to run …
=> UITEN-128 do not warn about dangling references

CHANGELOG.md, src/settings/LocationLibraries.js
https://issues.folio.org/browse/UITEN-80
The `locationsPerLibrary` query limit was set rather low, resulting in inaccurate location counts in the library list if the number of locations were too high. Could there be a library system out there with more than 10,000 locations? I hope not.
=> UITEN-80: Increase query limit for library locations

package.json, translations/ui-tenant-settings/en.json, translations/ui-tenant-settings/en_GB.json, translations/ui-tenant-settings/en_SE.json, translations/ui-tenant-settings/en_US.json
This PR removes two unused permissions:  `module.tenant-settings.enabled` and `ui-tenant-settings.module.enabled` and renames a displayName for `settings.tenant-settings.enabled` permission.
https://issues.folio.org/browse/UITEN-166
=> UITEN-166: Rename permission and cleanup unused permissions

CHANGELOG.md, package.json, src/settings/index.js
The key-bindings configured here were only functional in Settings >
Developer > Hotkeys test. Rather than providing a useful function, this
was just confusing since it gave the impression that bindings could be
usefully configured, rather than just configured for a POC.
Refs [UITEN-65](https://issues.folio.org/browse/UITEN-65)
=> UITEN-65 disable key-bindings

CHANGELOG.md, package.json
Managing service-points requires the ability to view staff-slips in
order to set which slips should be printed by default at any given
service-point. Read permission for staff slips was missing.
Add the missing permission.
Refs [UITEN-170](https://issues.folio.org/browse/UITEN-170)
=> UITEN-170 include staff-slips access in service-points pset

CHANGELOG.md, package.json
Upgrade `@folio/react-intl-safe-html` for compatibility with
`@folio/stripes` `v7` (react 17, react-intl 5).
Refs [UITEN-188](https://issues.folio.org/browse/UITEN-188), [STRIPES-769](https://issues.folio.org/browse/STRIPES-769)
=> UITEN-188 upgrade react-intl-safe-html

CHANGELOG.md, package.json, src/settings/LocationLocations/LocationDetail.js, src/settings/LocationLocations/LocationManager.js
Refactor away from `react-intl-safe-html`.
Issue: [UITEN-176](https://issues.folio.org/browse/UITEN-176)
=> UITEN-176: Refactor away from react-intl-safe-html

CHANGELOG.md, src/settings/LocationLocations/LocationDetail.js
View of services points doesn't update when clicking from one location to another
[UITEN-217](https://issues.folio.org/browse/UITEN-217) …
=> UITEN-217: View of services points doesn't update when clicking from one location to another

CHANGELOG.md, package.json, src/settings/ServicePoints/ConfirmPickupLocationChangeModal.js, src/settings/ServicePoints/ConfirmPickupLocationChangeModal.test.js, src/settings/ServicePoints/ServicePointForm.js, src/settings/ServicePoints/ServicePointForm.test.js, translations/ui-tenant-settings/en.json
Service Point Page - Add Confirm Pickup location change popup message
https://issues.folio.org/browse/UITEN-251
=> UITEN-251: Service Point Page - Add Confirm Pickup location change popup message

CHANGELOG.md, package.json, src/settings/index.js
We now check for the presence of relevant interfaces at run-time, and no make unsupported settings pages available when the relevant interfaces are not present.
Those interfaces (all to do with inventory) are now marked as optional in the package file.
It will be possible to simplify this code if/when support for the `iface` element is added to the `<Settings>` component, but the present fix does not depend on that future change: see https://github.com/folio-org/stripes-smart-components/pull/1401#issuecomment-1771403292
Fixes UITEN-266.
=> No errors when inventory-related interfaces are not present

CHANGELOG.md, src/settings/ServicePoints/ServicePointForm.js, src/settings/ServicePoints/ServicePointFormContainer.test.js, translations/ui-tenant-settings/en.json
https://folio-org.atlassian.net/browse/UITEN-274
We removed local `saveAndClose` label and replace it with `stripes-components.saveAndClose`. Also all related tests updated
=> UITEN-274: Use Save & close button label stripes-component translation key

CHANGELOG.md, package.json, translations/ui-tenant-settings/en.json
https://folio-org.atlassian.net/browse/UITEN-287 - Add “Settings (tenant): Can create, edit and remove reading room access” permission. …
=> UITEN-287 - Add new permission to create, edit and remove reading room access in tenant settings.

CHANGELOG.md, src/settings/ServicePoints/ServicePointForm.js, src/settings/ServicePoints/ServicePointForm.test.js
Disable edit of Routing service point field (ECS only)
https://issues.folio.org/browse/UITEN-285
=> UITEN-285: Disable edit of Routing service point field (ECS only)

CHANGELOG.md, package.json, src/settings/index.js
[UITEN-290](https://issues.folio.org/browse/UITEN-290) - Make dependency on mod-reading-rooms optional.
Earlier "reading-room" interface was included in okapiInterfaces and have been marked as BREAKING and the version in package.json was bumped up. This PR intends to correct the same by moving the interface into optionalOkapiInterfaces list and reverting the version in package.json. Also, changelog has been updated to remove "BREAKING" signature for earlier change.
Note: I don't see any other team worked on this module after it was marked as breaking change. Hence I think it is safe to revert and I don't think any other team needs to be informed of this change.
- Does this PR meet or exceed the …
=> UITEN-290 - Make dependency on mod-reading-rooms optional.

CHANGELOG.md, src/settings/ReadingRoomAccess/ReadingRoomAccess.js
[UITEN-298](https://folio-org.atlassian.net/browse/UITEN-298) - Incorrect translation id is being provided in reading room settings …
=> UITEN-298 - supply correct translation ids

CHANGELOG.md, src/settings/index.js, src/settings/index.test.js, test/jest/__new_mocks__/stripesCore.mock.js
[UITEN-301](https://folio-org.atlassian.net/browse/UITEN-301) - Display Reading room access in alphabetical order on settings page. …
=> UITEN-301 - Display Reading room access in alphabetical order on settings page.

CHANGELOG.md, package.json, translations/ui-tenant-settings/en.json
https://folio-org.atlassian.net/browse/UITEN-212
Here we updated permissions and translations for them according to the story.
=> UITEN-212: Permission changes for service point management

CHANGELOG.md, src/settings/ReadingRoomAccess/ReadingRoomAccess.js, src/settings/ReadingRoomAccess/ReadingRoomAccess.test.js, src/settings/ReadingRoomAccess/constant.js
[UITEN-304](https://folio-org.atlassian.net/browse/UITEN-304) - Reading room records checkboxes change state to opposite when edited
1. Reading rooms data is rendered on tenant settings page using ControlledVocab from stripes-smart-components.
In the hierarchy of rendering of components to render the list, ControlledVocab used case insensitive sort in [EditableList](https://github.com/folio-org/stripes-smart-components/blob/master/lib/EditableList/EditableList.js#L63).
This case-insensitive sort was not leveraged in the prop for `fieldComponents`.
This has been now added in order to address this bug.
2. the limit param has been modified to 25 as typically there would be maximum 25 reading rooms.
3. Some refactored was achieved.
Before merging this PR, please go through the following list …
=> UITEN-304 - Provide case insensitive sorted data to edit record, field components.

.eslintrc, CHANGELOG.md, src/settings/LocationLocations/LocationForm/RemoteStorageField.js, src/settings/ServicePoints/ServicePointForm.js, src/settings/ServicePoints/ServicePointFormContainer.js, test/jest/__mocks__/stripesCore.mock.js
Three-pronged approach:
* I disabled the `import/prefer-default-export` rule, since this module consistently uses a different style which is actually just fine.
* In the places where we had `react-hooks/exhaustive-deps` I have simply marked those lines with an `eslint-disable` comment, since my experience adding or removing dependencies to a hook can have subtle consequences that I'm not in a position to deal with right now. I marked each one individually rather than just disabling the rule, since each such warning _may_ be pointing out an actual bug, so someone ought to revisit these at some point.
* I simply fixed the remaining errors, such as missing `type` attributes in `<button>`s.
Fix UITEN-316.
=> Fix code to pass ESLint successfully.

src/settings/LocationLocations/LocationDetail.js, translations/ui-tenant-settings/en.json
Not as "disabled"
Part of UITEN-317.
=> UITEN-317 False FC value is displayed as <NoValue />

CHANGELOG.md, package.json, src/settings/LocationLocations/LocationDetail.js, translations/ui-tenant-settings/en.json
This commit merely declares the permissions.
Tomorrow I will do the work to test them in the UI: I can't do that until they come into existence, which will happen on the next build of snapshot.
Part of UITEN-318.
=> UITEN-318 Permissions to view and set floating collection

CHANGELOG.md, package.json, src/settings/LocationLocations/LocationDetail.js, src/settings/LocationLocations/LocationForm/LocationForm.js, src/settings/LocationLocations/LocationManager.js, translations/ui-tenant-settings/en.json
Settings > Tenant > Locations setup > Locations.
Permissions now govern viewing and editing floating collection.
Last part of UITEN-318.
=> UITEN-318 Permissions govern view/edit floating collection.

CHANGELOG.md, package.json, src/settings/ServicePoints/ServicePointDetail.js, src/settings/ServicePoints/ServicePointForm.js, translations/ui-tenant-settings/en.json
In Settings > Tenant > Service points: the detail page and edit form include support for the new `defaultCheckInActionForUseAtLocation` field, added to mod-inventory-storage in https://github.com/folio-org/mod-inventory-storage/pull/1212
Requires v3.5 of the `service-points` interface.
=> [UITEN-328] Service points: support `defaultCheckInActionForUseAtLocation` field
