folio-org/ui-tenant-settings

- Jenkinsfile
- src/settings/LocationLibraries.js
- test/bigtest/interactors/location-libraries.js
- test/bigtest/network/config.js
- test/bigtest/network/factories/campus.js
- test/bigtest/network/factories/institution.js
- test/bigtest/network/factories/library.js
- test/bigtest/network/factories/location.js
- test/bigtest/network/models/campus.js
- test/bigtest/network/models/institution.js
- test/bigtest/network/models/library.js
- test/bigtest/network/models/location.js
- test/bigtest/network/serializers/campus.js
- test/bigtest/network/serializers/institution.js
- test/bigtest/network/serializers/library.js
- test/bigtest/network/serializers/location.js
- test/bigtest/tests/location-libraries-test.js
https://issues.folio.org/browse/UIORG-163
This took a bit longer because of the tests...
> Fix campus filter. Part of UIORG-163

- src/settings/ServicePoints/ServicePointForm.js
https://issues.folio.org/browse/UITEN-4
> Fix permission name. Part of UITEN-4

- .gitignore
- package.json
- src/settings/Addresses.js
- src/settings/index.js
- test/bigtest/interactors/addresses.js
- test/bigtest/network/config.js
- test/bigtest/tests/addresses-test.js
- translations/ui-tenant-settings/en.json
https://issues.folio.org/browse/UINV-6
Purpose: The system needs a global list of addresses that relate directly to the institution. The invoice will draw on that list for Bill to and Ship to
> UINV-6 Add an address list to settings -> Tenant -> Addresses

- translations/ui-tenant-settings/ar.json
- translations/ui-tenant-settings/ca.json
- translations/ui-tenant-settings/da.json
- translations/ui-tenant-settings/de.json
- translations/ui-tenant-settings/en_GB.json
- translations/ui-tenant-settings/en_SE.json
- translations/ui-tenant-settings/en_US.json
- translations/ui-tenant-settings/es.json
- translations/ui-tenant-settings/es_419.json
- translations/ui-tenant-settings/es_ES.json
- translations/ui-tenant-settings/fr.json
- translations/ui-tenant-settings/fr_FR.json
- translations/ui-tenant-settings/hu.json
- translations/ui-tenant-settings/it_IT.json
- translations/ui-tenant-settings/pt_BR.json
- translations/ui-tenant-settings/pt_PT.json
- translations/ui-tenant-settings/zh_CN.json
> Update translation strings as of 20190529T122422

- CHANGELOG.md
- src/components/Period/Period.css
- src/components/Period/Period.js
- test/bigtest/interactors/service-point-create.js
- test/bigtest/tests/service-point-create-test.js
Mark Hold shelf expiration period as required in the scope of the [ticket](https://issues.folio.org/browse/UIORG-153)
> UIORG-153: Mark Hold shelf expiration period as required

- translations/ui-tenant-settings/ar.json
- translations/ui-tenant-settings/ca.json
- translations/ui-tenant-settings/da.json
- translations/ui-tenant-settings/de.json
- translations/ui-tenant-settings/en_GB.json
- translations/ui-tenant-settings/en_SE.json
- translations/ui-tenant-settings/en_US.json
- translations/ui-tenant-settings/es.json
- translations/ui-tenant-settings/es_419.json
- translations/ui-tenant-settings/es_ES.json
- translations/ui-tenant-settings/fr.json
- translations/ui-tenant-settings/fr_FR.json
- translations/ui-tenant-settings/hu.json
- translations/ui-tenant-settings/it_IT.json
- translations/ui-tenant-settings/pt_BR.json
- translations/ui-tenant-settings/pt_PT.json
- translations/ui-tenant-settings/zh_CN.json
> Update translation strings as of 20190612T145704

- translations/ui-tenant-settings/pt_BR.json
> Update translation strings as of 20190614T145022

- package.json
- src/settings/LocationLocations/LocationForm.js
- src/settings/LocationLocations/LocationManager.js
- test/bigtest/interactors/location-form.js
- test/bigtest/network/factories/location.js
- test/bigtest/tests/location-form-test.js
- to add an ability to merge async errors
- to handle contains quotation in query
https://issues.folio.org/browse/STCOM-408
> STCOM-408 - No uniqueness validation message on duplicate name

- src/settings/LocationLocations/DetailsField.js
- src/settings/ServicePoints/ServicePointDetail.js
- src/settings/ServicePoints/ServicePointForm.js
- test/bigtest/tests/service-point-create-test.js
- translations/ui-tenant-settings/en.json
Translate hardcoded strings
https://issues.folio.org/browse/UIORG-168
> UIORG-168 - Translate "Yes" and "No"

- translations/ui-tenant-settings/ar.json
- translations/ui-tenant-settings/ca.json
- translations/ui-tenant-settings/da.json
- translations/ui-tenant-settings/de.json
- translations/ui-tenant-settings/en_GB.json
- translations/ui-tenant-settings/en_SE.json
- translations/ui-tenant-settings/en_US.json
- translations/ui-tenant-settings/es.json
- translations/ui-tenant-settings/es_419.json
- translations/ui-tenant-settings/es_ES.json
- translations/ui-tenant-settings/fr.json
- translations/ui-tenant-settings/fr_FR.json
- translations/ui-tenant-settings/hu.json
- translations/ui-tenant-settings/it_IT.json
- translations/ui-tenant-settings/pt_BR.json
- translations/ui-tenant-settings/pt_PT.json
- translations/ui-tenant-settings/zh_CN.json
> Update translation strings as of 20190709T154346

- CHANGELOG.md
- package.json
- src/constants.js
- src/settings/LocationLocations/LocationDetail.js
- src/settings/LocationLocations/LocationForm.js
- src/settings/LocationLocations/LocationManager.js
- test/bigtest/interactors/location-details.js
- test/bigtest/interactors/location-form.js
- test/bigtest/interactors/locations.js
- test/bigtest/network/config.js
- test/bigtest/network/models/library.js
- test/bigtest/network/scenarios/locations.js
- test/bigtest/network/serializers/library.js
- test/bigtest/network/serializers/location.js
- test/bigtest/tests/location-form-test.js
- test/bigtest/tests/locations-test.js
- test/ui-testing/locations.js
Additionally includes changes for [UITEN-18](https://issues.folio.org/browse/UITEN-18).
>  UIORG-142: Refactor location locations functionality to get rid of `EntryManager` usage

- translations/ui-tenant-settings/pt_BR.json
> Update translation strings as of 20190711T172340

- CHANGELOG.md
- src/settings/LocationLocations/LocationDetail.js
- src/settings/LocationLocations/LocationForm.js
- src/settings/LocationLocations/LocationManager.js
- test/bigtest/interactors/location-details.js
- test/bigtest/interactors/location-form.js
- test/bigtest/tests/location-form-test.js
- test/bigtest/tests/locations-test.js
- translations/ui-tenant-settings/en.json
Relates to [UITEN-33](https://issues.folio.org/browse/UITEN-33).
> UITEN-33: Restore duplicate location for locations settings

- src/settings/LocationLocations/LocationForm.js
- src/settings/LocationLocations/ServicePointsFields.css
- src/settings/LocationLocations/ServicePointsFields.js
Go to Settings > Tenant > Service points > Create/Edit Location
If a required field label displays a double asterisk then update translation file
If a required field label displays text-color asterisk then update translation file and use the `required` prop for that field.
Before | After
------------ | -------------
> UICIRC-281: Delete unnecessary asterisks.

- translations/ui-tenant-settings/ja.json
> Update translation strings as of 20191101T131808

- translations/ui-tenant-settings/ar.json
> Update translation strings as of 20191113T152522

- src/settings/Addresses.js
https://issues.folio.org/browse/UIOR-459
> UIOR-459 Cannot save tenant address

- translations/ui-tenant-settings/es_ES.json
> Update translation strings as of 20191218T142024

- translations/ui-tenant-settings/es.json
- translations/ui-tenant-settings/es_419.json
> Update translation strings as of 20191220T210632

- translations/ui-tenant-settings/zh_CN.json
> Update translation strings as of 20200109T152437

- translations/ui-tenant-settings/fr_FR.json
> Update translation strings as of 20200117T173544

- package.json
- test/bigtest/interactors/location-details.js
- test/bigtest/interactors/location-form.js
https://issues.folio.org/browse/UITEN-71
> UITEN-71 Tenant / Addresses: Last updated by - Username not displayed

- src/settings/Locale.js
Eyeballing this change without testing the code.  Please verify syntax.
> Add Urdu language

- CHANGELOG.md
- PULL_REQUEST_TEMPLATE.md
- package.json
https://issues.folio.org/browse/UITEN-72 …
> UITEN-72 Security update eslint to >= 6.2.1 or eslint-util >= 1.4.1

- CHANGELOG.md
- src/settings/ServicePoints/ServicePointForm.js
https://issues.folio.org/browse/UITEN-86 …
> UITEN-86 Settings > Tenant > Service Point > Detail Record updates

- CHANGELOG.md
- src/settings/Bindings/BindingsForm.js
- src/settings/LocationLocations/LocationDetail.js
- src/settings/LocationLocations/LocationForm.js
- src/settings/Plugins/PluginForm.js
- src/settings/ServicePoints/ServicePointForm.js
- test/bigtest/interactors/location-details.js
- test/bigtest/interactors/location-form.js
- test/bigtest/tests/location-form-test.js
- test/bigtest/tests/locations-test.js
- translations/ui-tenant-settings/en.json
https://issues.folio.org/browse/UITEN-87 …
> UITEN-87 Settings > Tenant > Location Setup > New Location

- translations/ui-tenant-settings/ar.json
- translations/ui-tenant-settings/ca.json
- translations/ui-tenant-settings/da.json
- translations/ui-tenant-settings/de.json
- translations/ui-tenant-settings/en_GB.json
- translations/ui-tenant-settings/en_SE.json
- translations/ui-tenant-settings/en_US.json
- translations/ui-tenant-settings/es.json
- translations/ui-tenant-settings/es_419.json
- translations/ui-tenant-settings/es_ES.json
- translations/ui-tenant-settings/fr.json
- translations/ui-tenant-settings/fr_FR.json
- translations/ui-tenant-settings/he.json
- translations/ui-tenant-settings/hu.json
- translations/ui-tenant-settings/it_IT.json
- translations/ui-tenant-settings/ja.json
- translations/ui-tenant-settings/pt_BR.json
- translations/ui-tenant-settings/pt_PT.json
- translations/ui-tenant-settings/ru.json
- translations/ui-tenant-settings/ur.json
- translations/ui-tenant-settings/zh_CN.json
- translations/ui-tenant-settings/zh_TW.json
> Update translation strings as of 20200407T170213

- CHANGELOG.md
- src/settings/LocationLocations/LocationDetail.js
- src/settings/LocationLocations/LocationForm.js
- src/settings/LocationLocations/LocationInUseModal.js
- src/settings/LocationLocations/LocationManager.js
- test/bigtest/interactors/location-details.js
- test/bigtest/interactors/location-form.js
- test/bigtest/tests/locations-test.js
https://issues.folio.org/browse/UITEN-88 …
> UITEN-88 Settings > Tenant > Location Setup > Edit/View Location

- CHANGELOG.md
- package.json
- src/settings/LocationLocations/LocationManager.js
> Refuse to delete locations in use by a course-listing or a course-reserve

- translations/ui-tenant-settings/fr_FR.json
- translations/ui-tenant-settings/pt_BR.json
> Update translation strings as of 20200409T134057

- CHANGELOG.md
- src/components/Period/Period.css
- src/components/RepeatableField/FieldRow.js
- src/components/RepeatableField/RepeatableField.css
- src/settings/LocationLocations/ServicePointsFields.css
- src/settings/LocationLocations/ServicePointsFields.js
- src/settings/Plugins/Plugins.js
- src/settings/SSOSettings/SSOSettings.js
https://issues.folio.org/browse/UITEN-32 …
> UITEN-32 Remove hardcoded font sizes

- README.md
See [FOLIO-2572](https://issues.folio.org/browse/FOLIO-2572) and [STCLI-148](https://issues.folio.org/browse/STCLI-148)
Also Update copyright year FOLIO-1021
> FOLIO-2572 STCLI-148 verify new jenkins-slave-all, stripes-cli, optionalOkapiInterfaces

- translations/ui-tenant-settings/zh_TW.json
> Update translation strings as of 20200513T135229

- CHANGELOG.md
- src/settings/Locale.js
- src/settings/LocationLocations/ServicePointsFields.js
https://issues.folio.org/browse/UITEN-94 …
> UITEN-94 Accessibility Error: Form elements must have labels

- package.json
> Use 'actsAs' instead of the deprecated 'type'

- CHANGELOG.md
- src/settings/ServicePoints/ServicePointForm.js
https://issues.folio.org/browse/UITEN-97 …
> UITEN-97 Accessibility Error: IDs used in ARIA and labels must be unique

- CHANGELOG.md
- package.json
[MODLOGSAML-60](https://issues.folio.org/browse/MODLOGSAML-60) creates breaking changes to the login-saml interface.  It also introduces new permissions for GET/PUT /saml/configuration.
This PR is to make the necessary adjustments.
See [UITEN-103](https://issues.folio.org/browse/UITEN-103)
Bump the login-saml interface version and fix the related permissions
- Do PRs exist for these …
> UITEN-103 - new login-saml interface and permissions

- src/settings/ServicePoints/utils.js
https://issues.folio.org/browse/UITEN-76 …
> UITEN-76 missed validateion

- CHANGELOG.md
- src/settings/Plugins/Plugins.js
The resource query was missing a limit clause.
Refs [UITEN-107](https://issues.folio.org/browse/UITEN-107)
> UITEN-107 retrieve plugin data for 1000 records

- translations/ui-tenant-settings/it_IT.json
> Update translation strings as of 20200824T140725

- CHANGELOG.md
- package.json
Refs [UITEN-112](https://issues.folio.org/browse/UITEN-112)
> UITEN-112 increment react-intl to v5

- CHANGELOG.md
- src/settings/SSOSettings/SSOSettings.js
- src/settings/SSOSettings/SamlForm.js
- test/bigtest/interactors/sso-settings.js
- test/bigtest/network/scenarios/sso-settings.js
- test/bigtest/tests/sso-settings-test.js
Fix Idp Url validator.
https://issues.folio.org/browse/UITEN-114
I could not get this to pass with BigTest with `validateOnBlur` option so I removed it. The validation just didn't work correctly even after values were entered. I think this was a left over from when there was no `save` button and the values were saved automatically.
> UITEN-114: Fix Idp Url validator

- translations/ui-tenant-settings/ar.json
- translations/ui-tenant-settings/ca.json
- translations/ui-tenant-settings/da.json
- translations/ui-tenant-settings/de.json
- translations/ui-tenant-settings/en_GB.json
- translations/ui-tenant-settings/en_SE.json
- translations/ui-tenant-settings/en_US.json
- translations/ui-tenant-settings/es.json
- translations/ui-tenant-settings/es_419.json
- translations/ui-tenant-settings/es_ES.json
- translations/ui-tenant-settings/fr.json
- translations/ui-tenant-settings/fr_FR.json
- translations/ui-tenant-settings/he.json
- translations/ui-tenant-settings/hi_IN.json
- translations/ui-tenant-settings/hu.json
- translations/ui-tenant-settings/it_IT.json
- translations/ui-tenant-settings/ja.json
- translations/ui-tenant-settings/ko.json
- translations/ui-tenant-settings/pl.json
- translations/ui-tenant-settings/pt_BR.json
- translations/ui-tenant-settings/pt_PT.json
- translations/ui-tenant-settings/ru.json
- translations/ui-tenant-settings/ur.json
- translations/ui-tenant-settings/zh_CN.json
- translations/ui-tenant-settings/zh_TW.json
> Update translation strings as of 20201013T203429

- CHANGELOG.md
- package.json
- src/settings/Bindings/BindingsForm.js
- src/settings/LocationLocations/LocationDetail.js
[[UITEN-118]](https://issues.folio.org/browse/UITEN-118)
Release v5.0.0
* Updated `CHANGELOG.md` and `package.json`
* Fixed lint warnings
Note: suppresed some lint warning due to lint bugging out and still throwing warning after fix
> UITEN-118: Release v5.0.0

- translations/ui-tenant-settings/ar.json
- translations/ui-tenant-settings/ca.json
- translations/ui-tenant-settings/da.json
- translations/ui-tenant-settings/de.json
- translations/ui-tenant-settings/en_GB.json
- translations/ui-tenant-settings/en_SE.json
- translations/ui-tenant-settings/en_US.json
- translations/ui-tenant-settings/es.json
- translations/ui-tenant-settings/es_419.json
- translations/ui-tenant-settings/es_ES.json
- translations/ui-tenant-settings/fr.json
- translations/ui-tenant-settings/fr_FR.json
- translations/ui-tenant-settings/he.json
- translations/ui-tenant-settings/hi_IN.json
- translations/ui-tenant-settings/hu.json
- translations/ui-tenant-settings/it_IT.json
- translations/ui-tenant-settings/ja.json
- translations/ui-tenant-settings/ko.json
- translations/ui-tenant-settings/pl.json
- translations/ui-tenant-settings/pt_BR.json
- translations/ui-tenant-settings/pt_PT.json
- translations/ui-tenant-settings/ru.json
- translations/ui-tenant-settings/ur.json
- translations/ui-tenant-settings/zh_CN.json
- translations/ui-tenant-settings/zh_TW.json
> Update translation strings as of 20201026T135354

- CHANGELOG.md
- src/settings/SSOSettings/SamlForm.js
- test/bigtest/helpers/setup-application.js
- test/bigtest/interactors/sso-settings.js
- test/bigtest/tests/sso-settings-test.js
https://issues.folio.org/browse/UITEN-132
Do not show download metadata button without correct perms.
> UITEN-132: Do not show download metadata button without correct perms

- CHANGELOG.md
- package.json
Update module version and changelog after bugfix v5.0.1 release in the scope of the [UITEN-130](https://issues.folio.org/browse/UITEN-130).
> UITEN-130: Update module version and changelog after bugfix v5.0.1 release

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UITEN-127
Add additional permission to location permission set.
> UITEN-127: Add additional permission to location permission set

- .gitignore
- CHANGELOG.md
- package.json
- src/settings/LocationLocations/LocationForm.js
- src/settings/LocationLocations/LocationManager.js
- src/settings/LocationLocations/ServicePointsFields.js
UITEN-119 Add permissions, fix previous console warnings
Create remote storage flag in Settings > Tenant > Locations
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> UITEN-119 Add permissions, fix previous console warnings

- CHANGELOG.md
- jest.config.js
- package.json
> UITEN-119 Add remote-storage back-end module dependency

- CHANGELOG.md
- package.json
UITEN-119 Fix back-end remote-storage dependencies
While it's helpful for reviewers to help …
> UITEN-119 Fix back-end remote-storage dependencies

- CHANGELOG.md
- jest.config.js
- package.json
- src/components/Period/Period.js
- src/settings/Bindings/Bindings.test.js
- src/settings/Bindings/BindingsForm.js
- src/settings/Plugins/PluginForm.js
- src/settings/Plugins/Plugins.js
- src/settings/Plugins/Plugins.test.js
- test/bigtest/tests/service-point-create-test.js
- test/jest/helpers/renderWithRouter.js
- test/jest/jest.setup.js
Update `stripes` to `v6.0.0` in the scope of the [UITEN-146](https://issues.folio.org/browse/UITEN-146).
> UITEN-146: Update `stripes` to `v6.0.0`

- src/settings/LocationLocations/RemoteStorage/Provider.js
> UITEN-119 Fix missing reset

- .stripesclirc.js
- CHANGELOG.md
- package.json
- src/settings/BursarExports/BursarExports.js
- src/settings/BursarExports/BursarExports.test.js
- src/settings/BursarExports/index.js
- src/settings/index.js
- translations/ui-tenant-settings/en.json
https://issues.folio.org/browse/UITEN-152 …
> UITEN-152 Bursar exports settings page

- CHANGELOG.md
- src/settings/BursarExports/BursarExports.js
- src/settings/BursarExports/BursarExports.test.js
- src/settings/BursarExports/BursarExportsConfiguration/BursarExportsConfiguration.js
- src/settings/BursarExports/BursarExportsConfiguration/BursarExportsConfiguration.test.js
- src/settings/BursarExports/BursarExportsConfiguration/constants.js
- src/settings/BursarExports/BursarExportsConfiguration/index.js
- src/settings/BursarExports/BursarExportsConfiguration/validation.js
- translations/ui-tenant-settings/en.json
https://issues.folio.org/browse/UITEN-156 …
> UITEN-156 Bursar exports configuration form

- CHANGELOG.md
- package.json
- translations/ui-tenant-settings/en.json
> UITEN-158 Update stripes-cli to v2

- CHANGELOG.md
- src/settings/LocationLocations/LocationDetail.js
- src/settings/LocationLocations/RemoteStorage/Provider.js
https://issues.folio.org/browse/UITEN-162 …
> UITEN-162 Remote Storage configuration should be removed

- src/settings/LocationLocations/LocationDetail.js
- src/settings/LocationLocations/LocationForm/LocationForm.js
- src/settings/LocationLocations/LocationForm/RemoteStorageField.js
- src/settings/LocationLocations/RemoteStorage/Provider.js
https://issues.folio.org/browse/UITEN-151 …
> UITEN-151 fix errors

- package.json
https://issues.folio.org/browse/UITEN-159 …
> UITEN-159 remove unused permission

- CHANGELOG.md
- package.json
In the scope of [UITEN-157](https://issues.folio.org/browse/UITEN-157).
ui-tenant-settings v6.0.0 release.
> UITEN-157: Release v6.0.0

- CHANGELOG.md
> UITEN-157: Update CHANGELOG.md

- CHANGELOG.md
- package.json
Release v6.1.0 in the scope of the [UITEN-177](https://issues.folio.org/browse/UITEN-177).
> UITEN-177: Release v6.1.0

- CHANGELOG.md
- src/settings/LocationLocations/RemoteStorageDetails.js
- src/settings/LocationLocations/remoteStorageDetails.test.js
https://issues.folio.org/browse/UITEN-180 …
> UITEN-180 The Remote storage section is not displayed in the General Information pane

- CHANGELOG.md
- package.json
- src/settings/LocationLocations/RemoteStorage/Provider.js
- src/settings/LocationLocations/RemoteStorageDetails.js
- src/settings/LocationLocations/remoteStorageDetails.test.js
https://issues.folio.org/browse/UITEN-182 …
> Release 6.1.1

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UITEN-178 …
> UITEN-178 permission sets should avoid ".all" permissions

- src/settings/SSOSettings/SSOSettings.test.js
- test/bigtest/tests/service-point-update-test.js
https://issues.folio.org/browse/UITEN-140 …
> Rewrite Bigtest tests for SSO settings page with jest/react-testing-library

- src/settings/LocationLibraries.js
- src/settings/LocationLibraries.test.js
https://issues.folio.org/browse/UITEN-144 …
> UITEN-144: Rewrite Bigtest tests for Libraries page with jest/react-testing-library

- src/constants.js
https://issues.folio.org/browse/UITEN-197
https://issues.folio.org/browse/MODLOGSAML-104
> Fix incorrect user property email UITEN-197

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UITEN-187 …
> refactor psets away from backend .all permissions

- CHANGELOG.md
- src/settings/LocationLocations/LocationManager.js
https://issues.folio.org/browse/UITEN-201 …
> UITEN-201: Locations not visible in Settings > Tenant > Locations if more than 1000 locations exist on one library

- CHANGELOG.md
- src/settings/LocaleForm.js
https://issues.folio.org/browse/UITEN-200 …
> UITEN-200 Language and localization > locale dropdown should be sorted in current locale

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- package.json
- src/components/Period/Period.js
- src/components/Period/Period.test.js
- src/components/RepeatableField/FieldRow.js
- src/components/RepeatableField/RepeatableField.test.js
https://issues.folio.org/browse/UITEN-209 …
> UITEN-209  Improve in ui-tenant-settings test coverage with jest/RTL to 80%

- CHANGELOG.md
- package.json
Unable to modify tenant language and localization settings with ui-tenant-settings.settings.locale assigned
https://issues.folio.org/browse/UITEN-211
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
> UITEN-211:Unable to modify tenant language and localization settings with ui-tenant-settings.settings.locale assigned

- CHANGELOG.md
- package.json
ui-tenant-settings.settings.enabled does not function as expected
[UITEN-224](https://issues.folio.org/browse/UITEN-224)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> UITEN-224: ui-tenant-settings.settings.enabled does not function as expected

- CHANGELOG.md
- src/settings/LocaleForm.js
[UITEN-230](https://issues.folio.org/browse/UITEN-230)
While it's helpful for reviewers to …
> UITEN-230:Convert "Change session locale" from button to plain text link

- CHANGELOG.md
- package.json
- src/settings/LocationCampuses.js
https://issues.folio.org/browse/UITEN-226 …
> UITEN-226 View-only access to Settings > Tenant > Location setup > Campuses

- CHANGELOG.md
- src/components/Period/Period.js
- src/components/Period/Period.test.js
- src/settings/ServicePoints/ServicePointForm.js
- src/settings/ServicePoints/ServicePointFormContainer.js
- src/settings/ServicePoints/ServicePointManager.js
Update 'Closed library date management for hold shelf expiration date calculation' menu
Issue: https://issues.folio.org/browse/UITEN-237 …
> UITEN-237 - Update 'Closed library date management for hold shelf expiration date calculation' menu

- .eslintrc
- CHANGELOG.md
- package.json
- src/settings/LocationLocations/LocationForm/LocationForm.js
- src/settings/LocationLocations/LocationForm/ServicePointsFields.js
- src/settings/ServicePoints/StaffSlipEditList.js
replace babel-eslint with @babel/eslint-parser
Issue: https://issues.folio.org/browse/UITEN-214
1. replaced babel-eslint dev dependency with @babel/eslint-parser
2. added new eslint libraries eslint-import-resolver-alias eslint-import-resolver-webpack @babel/core eslint@^7.32.0 @folio/eslint-config-stripes@^6.1.0
3. updated .eslintrc file to pick @babel/eslint-parser as parser
4. fixed few lint issues
- Are the JIRAs under active …
> UTEN-214 - replace babel-eslint with @babel/eslint-parser

- CHANGELOG.md
- src/settings/ServicePoints/ServicePointFormContainer.js
https://issues.folio.org/browse/UITEN-238 …
> UITEN-238: Unable to save service point on FOLIO snapshot or snapshot-2

- CHANGELOG.md
- package.json
> Release 7.4.0

- CHANGELOG.md
- src/settings/LocationLocations/LocationManager.js
https://issues.folio.org/browse/UITEN-234 …
> UITEN-234 Remember value in Institutions, campuses and libraries dropown (Settings > Tenant > Locations) when navigating away from page and returning

- CHANGELOG.md
- src/settings/LocationCampuses.js
- src/settings/LocationCampuses.test.js
- src/settings/LocationInstitutions.css
- src/settings/LocationInstitutions.js
- src/settings/LocationInstitutions.test.js
- src/settings/LocationLibraries.js
[UITEN-248](https://issues.folio.org/browse/UITEN-248)
While it's helpful for reviewers to …
> UITEN-248: Improve "Number of locations" on Campuses page

- CHANGELOG.md
- src/settings/Addresses.js
- src/settings/LocaleForm.js
- src/settings/Plugins/PluginForm.js
- src/settings/Plugins/Plugins.js
- src/settings/Plugins/Plugins.test.js
- src/settings/SSOSettings/SSOSettings.js
- src/settings/SSOSettings/SSOSettings.test.js
- src/settings/SSOSettings/SamlForm.js
- src/settings/ServicePoints/ServicePointManager.js
https://issues.folio.org/browse/UITEN-256 …
> UITEN-256 Need new permission(s) to view all Tenant settings in UI - General tab

- CHANGELOG.md
- src/settings/Addresses.js
- src/settings/Locale.js
- src/settings/LocationCampuses.js
- src/settings/LocationInstitutions.js
- src/settings/LocationInstitutions.test.js
- src/settings/LocationLibraries.js
- src/settings/LocationLibraries.test.js
- src/settings/LocationLocations/LocationDetail.js
- src/settings/LocationLocations/LocationForm/LocationFormContainer.js
- src/settings/LocationLocations/LocationManager.js
- src/settings/LocationLocations/locationDetail.test.js
- src/settings/Plugins/Plugins.js
- src/settings/Plugins/Plugins.test.js
- src/settings/SSOSettings/SSOSettings.js
- src/settings/SSOSettings/SSOSettings.test.js
- src/settings/SSOSettings/SamlForm.js
- src/settings/ServicePoints/ServicePointDetail.js
- src/settings/ServicePoints/ServicePointFormContainer.js
- src/settings/ServicePoints/ServicePointManager.js
- src/settings/index.js
- test/jest/__mocks__/stripesCore.mock.js
- test/jest/__new_mocks__/stripesCore.mock.js
- translations/ui-tenant-settings/en.json
…ow this format - <<App name>> settings - <<selected page name>> - FOLIO
[UITEN-257](https://issues.folio.org/browse/UITEN-257)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> UITEN-257: Tenant settings: Ensure your settings HTML page title follow this format - <<App name>> settings - <<selected page name>> - FOLIO

- CHANGELOG.md
- src/settings/Addresses.test.js
- src/settings/LocationLocations/LocationForm/LocationForm.js
- src/settings/LocationLocations/LocationForm/LocationFormContainer.test.js
- src/settings/LocationLocations/LocationManager.test.js
- test/jest/__mocks__/index.js
- test/jest/__mocks__/resizeObserver.mock.js
https://folio-org.atlassian.net/browse/UITEN-273
Updated translation key for `Save & close` button. Also, the required tests were updated.
> UITEN-273: Use Save & close button label stripes-component translation key

- CHANGELOG.md
- jest.config.js
- package.json
- translations/ui-tenant-settings/en.json
https://folio-org.atlassian.net/browse/UITEN-286 - Add “Settings (tenant): Can view reading room access” permission
Add new interface in okapiInterface of package.json. 
Add a new permission to view reading room access within tenant settings, with visibility true, as it should be assignable to a user from user UI.
As new interface was added, this change is marked as breaking in changelog and major version has been updated.
Marking a breaking change when a new interface is added to a module.
- What other modules will these …
> UITEN-286 - Add new permission to view reading room access in tenant settings.

- CHANGELOG.md
- package.json
- src/hooks/useCirculationSettingsEcsTlrFeature/useCirculationSettingsEcsTlrFeature.test.js
- src/settings/ServicePoints/ServicePointFormContainer.js
- Fix saving problem for routing service point(ECS only)
- Covered by test 1 file
https://issues.folio.org/browse/UITEN-306
> UITEN-306: Fix saving problem for routing service point(ECS only)

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
> bump up upload actions v3

- package.json
> bump up module version

- CHANGELOG.md
- src/settings/LocationLocations/LocationForm/DetailsField.js
- src/settings/LocationLocations/LocationForm/LocationFormContainer.js
- src/settings/LocationLocations/LocationForm/RemoteStorageField.js
- src/settings/LocationLocations/LocationForm/ServicePointsFields.js
- src/settings/LocationLocations/LocationManager.js
https://folio-org.atlassian.net/browse/UITEN-302
Here we fixed some ui bugs after code refactoring
https://github.com/user-attachments/assets/78b57486-a99c-4e11-8d56-68086a459826
> UITEN-302: Address existing UI issues on Settings > Tenant > Locations

- CHANGELOG.md
- src/settings/LocationLocations/LocationForm/LocationForm.js
- src/settings/LocationLocations/LocationForm/LocationFormContainer.test.js
- src/settings/LocationLocations/LocationManager.js
- translations/ui-tenant-settings/en.json
Settings > Tenant > Locations setup > Locations.
Fixes UITEN-314.
> UITEN-314 Enable and Display floating collection for locations

- CHANGELOG.md
- src/settings/LocationLocations/LocationDetail.js
- translations/ui-tenant-settings/en.json
Settings > Tenant > Locations setup > Locations. Display in detailed view when floating collection is enabled or not enabled.
Fixes UITEN-317.
> UITEN-317 Detailed view shows Floating Collection bit

- src/settings/LocationLocations/LocationForm/LocationFormContainer.js
> UITEN-324 Fix issue with openin location form
